name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install ngrok
        run: |
          # Download the latest ngrok version
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz
          
          # Extract ngrok and move it to /usr/local/bin
          sudo tar -xvzf ngrok.tgz -C /usr/local/bin

          # Clean up by removing the downloaded tar file
          rm ngrok.tgz

      - name: Authenticate ngrok
        run: |
          # Authenticate ngrok with the provided token
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start ngrok Tunnel in Loop
        run: |
          # Start ngrok tunnel in the background
          ngrok tcp 22 &

          # Keep the script running
          while true; do sleep 1000; done

      - name: Enable SSH (if not already enabled)
        run: |
          # Ensure SSH is installed and running
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh
